print("Hello World")
print("Hey, I'm learning Python3")
print("Python is easy, case-sensitive and portable language")
print("Python is the implicit typed language.")
print("Developed by Guido van Rossum","\n")
print("Let's get started", "\n")
print("Charachter set of python is:- ")
print("Letter- 'a' to 'z' & 'A' to 'Z' ")
print("Digits- '0' to '9' ")
print("secial charachters- '*','@','#',etc")
print(23)
print(23, 45 ,"\n")
print("Variables in Python","Name given to any memory location.")
print('name = "Shradha"') #string defination
print("age = 23")  #integer defination
print("price = 89.57","\n")  #float defination
print("Identifiers in python:-", "Name given to the variable is refers to identifiers","\n")
print("Get the type of the variable")
print("type(variable_name)", "\n")
print("Keywords:-","Keywords are reserved words in python","\n")
print("Token:-", "Tokens are the smallest fraction of the program")
print("Types of Token")
print("Panctuator")
